### ISSUE TITLE
Add new sub-section to Events & Exhibitions: 'Exhibition Programs'

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#107]
Will contain information on: Events, Exhibitions, Off-Site, Salons

Should mimic the existing 'Programs' page under 'Residencies'

**Comment by coreytegeler** [comment]
should there be anything else in the subnav besides this? maybe I can add back in the links to event types?

**Comment by coreytegeler** [comment]
got the pages and custom fields setup. i may need to fix up some things as they go about adding in the content
