### ISSUE TITLE
Remove today's end date on related events to residents

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#109]
![screen shot 2016-02-19 at 11 09 40 am](https://cloud.githubusercontent.com/assets/1727034/13181122/75e4373e-d6f9-11e5-8e6c-a229e8843f6b.png)

**Comment by phillubliner** [comment]
I think this instance just doesn't have an end date, so nothing should display.

**Comment by phillubliner** [comment]
This one has a start date, no end date, but has today's date for both. http://othermeans.us/client/iscp/resident/polibio-diaz

**Comment by coreytegeler** [comment]
oops, very old broken function forgot to delete
