### ISSUE TITLE
Participating resident image getting squished

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#112]
http://othermeans.us/client/iscp/event/salon-hannah-heilmann-and-mark-hilton

![screen shot 2016-02-19 at 11 20 35 am](https://cloud.githubusercontent.com/assets/1727034/13181382/e6e0e1e8-d6fa-11e5-9d92-76f1f7d45aa5.png)

**Comment by coreytegeler** [comment]
good bc i really don't like that image

**Comment by coreytegeler** [comment]
now a text list
