### ISSUE TITLE
Description/Bio text styles

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#116]
Is there something we can do in the CSS to try and override these bummer styles that get imported occasionally?
http://othermeans.us/client/iscp/resident/jason-wing

Like `` .bio div { font-family: ………… !important } `` ?

**Comment by phillubliner** [comment]
If not, we might need to turn on HTML features in the WYSIWYG editors so ISCP can remove it manually.

**Comment by coreytegeler** [comment]
i added some fixes in there, let me know if you notice some bad stuff elsewhere
