### ISSUE TITLE
WP: add filters on Events and Residents overviews in dashboard

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#121]

**Comment by phillubliner** [comment]
https://wordpress.org/plugins/codepress-admin-columns/

**Comment by phillubliner** [comment]
Might be helpful to add this too: http://coffee2code.com/wp-plugins/admin-post-navigation/

**Comment by coreytegeler** [comment]
The admin nav is up, but...
<img width="441" alt="screen shot 2016-02-24 at 11 23 07 am" src="https://cloud.githubusercontent.com/assets/3860295/13292255/14448aa8-dae9-11e5-996a-fb59c094ed6a.png">
