### ISSUE TITLE
Residents: extra punctuation showing up on captions

### ISSUE THREAD

**Issue by OtherMeans** [OtherMeans/iscp-wp-theme#124]
John Kørner's page: 

![screen shot 2016-02-26 at 5 38 24 pm](https://cloud.githubusercontent.com/assets/4854832/13367342/d0e6e3be-dcaf-11e5-9bc0-ec2f0dad760d.png)
![screen shot 2016-02-26 at 5 38 18 pm](https://cloud.githubusercontent.com/assets/4854832/13367343/d0ec919c-dcaf-11e5-99c1-52a4d5918318.png)

**Comment by coreytegeler** [comment]
took care of this, leaving open for any other mistakes that may show up

i have also come across examples where content was entered incorrectly (i.e. spaces at end of text)
