### ISSUE TITLE
WP: change default posts order in admin

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#125]
Newest->Oldest by Start Date

if that's not possible, just by Title alpha.

**Comment by phillubliner** [comment]
http://wordpress.stackexchange.com/questions/66455/how-to-change-order-of-posts-in-admin

**Comment by coreytegeler** [comment]
for residents or events? or both? if residents, this is still a problem that even that plugin cannot solve. events can be done

**Comment by phillubliner** [comment]
Just Events is ok
