### ISSUE TITLE
Groundfloor resident add-ons

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#14]
Display "Groundfloor" in lieu of Sponsor on:
* Residents Overview (in resident excerpt info)
* Top of Resident Page
* Related Resident Excerpt
* Wordpress Residents Overview (in sponsor column)

**Comment by coreytegeler** [comment]
ground floor residents still have sponsors so I don't think it should replace sponsors, but I added it into these locations

also, I replaced the 'Residents from [Country]' section with 'Ground Floor Residents' on the appropriate resident pages
