### ISSUE TITLE
Event excerpt: Move time to after date on same line, use endash

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#156]
Should be: March 9, 2016, 11am–12:30pm

**Comment by phillubliner** [comment]
![screen shot 2016-03-08 at 2 13 32 pm](https://cloud.githubusercontent.com/assets/1727034/13612949/f7223a98-e537-11e5-93b7-0cd63da9453b.png)

**Comment by coreytegeler** [comment]
as for the en dash, the time is now one field since there was no need to programmatically handle the fields so they will have to enter that

**Comment by phillubliner** [comment]
ok
