### ISSUE TITLE
"Upcoming Events & Exhibitions" should say "Current and Upcoming Events & Exhibitions"

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#161]

**Comment by coreytegeler** [comment]
where should this change be?

**Comment by phillubliner** [comment]
Let's just change it in the overview page header

![screen shot 2016-03-09 at 10 24 59 am](https://cloud.githubusercontent.com/assets/1727034/13639996/31da8c36-e5e1-11e5-9826-17f1290a06a3.png)
