### ISSUE TITLE
Wordpress: add Gallery image issues

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#17]
I'm adding a new test event and want to add images to it that are already in the media library. When I click into the Gallery to add an image it says No Items Found in the Media Library. 

Ideally it shows the full Media Library options and automatically caries over caption information if/when you select the image.

**Comment by coreytegeler** [comment]
this is a parameter with the custom field, i just switched it on event galleries

let me know if you see this somewhere else
