### ISSUE TITLE
Remove caption field in the Image section

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#201]
We don't use this, right?

![screen shot 2016-03-28 at 10 22 46 am](https://cloud.githubusercontent.com/assets/1727034/14079874/1b8dbc1c-f4cf-11e5-85ba-cd43ee7d5df3.png)

**Comment by coreytegeler** [comment]
thats default wordpress stuff

**Comment by phillubliner** [comment]
No override?
