### ISSUE TITLE
Super nav: line spacing

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#22]
![screen shot 2015-12-15 at 4 27 52 pm](https://cloud.githubusercontent.com/assets/1727034/11824617/db0ceb7c-a348-11e5-903e-7249172ff3bc.png)

Lines should end at the same gap distance.

**Comment by coreytegeler** [comment]
<img width="1015" alt="screen shot 2015-12-16 at 12 06 42 pm" src="https://cloud.githubusercontent.com/assets/3860295/11847883/84b9dd2a-a3ed-11e5-99fe-737b688478cd.png">

also put the same distance (20px) between the center line and the top/bottom of the window,

**Comment by phillubliner** [comment]
Sorry, they should actually all be at the smaller 10px distance.
