### ISSUE TITLE
media overlay spec

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#23]
Cursor is X icon.

![screen shot 2015-12-15 at 4 32 09 pm](https://cloud.githubusercontent.com/assets/1727034/11824754/994be3fe-a349-11e5-9827-83e171fe2407.png)

**Comment by coreytegeler** [comment]
what's the rule with that X there?

**Comment by coreytegeler** [comment]
and should this be a carousel when there are multiple images available?

**Comment by phillubliner** [comment]
when there's a popup overlay, the cursor would be an X, and any click would close the overlay

carousel would be great — maybe the cursor can be a left or right arrow icon when it's closer to the sides
