### ISSUE TITLE
filter dropdowns

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#4]

**Comment by phillubliner** [comment]
![screen shot 2015-12-14 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/1727034/11796119/91f1340e-a288-11e5-98de-089f644357b1.png)

![screen shot 2015-12-14 at 5 32 08 pm](https://cloud.githubusercontent.com/assets/1727034/11796135/a56a08b2-a288-11e5-9735-93ebd0de8168.png)

**Comment by phillubliner** [comment]
Filter dropdown area should "push down" the resident grid.

**Comment by coreytegeler** [comment]
the post count may be an issue, it'll require a loop within a loop which may be too much for the server to handle

**Comment by coreytegeler** [comment]
forget that ^

got it workin
