### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#46]
Not sure where this stands at the moment with development. Needs design though.

**Comment by coreytegeler** [comment]
got this setup similar to the overview pages, but a few decisions need to be made
* search field in nav
* filter system
* tile for sponsor/page without images in grid

**Comment by phillubliner** [comment]
* can search field in nav display how many results on the fly (below the search entry)?
* search box should be on results page at top, separated by a rule
* use 'list' style view in columns (similar to Sponsors overview) showing: small thumbnail (if exists); title; page type
