### ISSUE TITLE
Add 'Current Residents' to right side on Home

### ISSUE THREAD

**Issue by OtherMeans** [OtherMeans/iscp-wp-theme#69]
Visit to left side maybe for now?

**Comment by phillubliner** [comment]
Let's add 'Visit' to left side of Home.

**Comment by phillubliner** [comment]
Also, when you slide to Current Residents, it should have the same LEFT/RIGHT that it has when you click on it from the super nav.

**Comment by coreytegeler** [comment]
you want to slide from home and then have the homepage inaccessible to slide back to?

**Comment by phillubliner** [comment]
yeah. moving from homepage will have to be the exception. don’t think it ever needs to be in the left/right logic.
