### ISSUE TITLE
To-Do List (12/15)

### ISSUE THREAD

**Issue by coreytegeler** [OtherMeans/iscp-wp-theme#7]
1st Priority
* Residents overview page w/ working links and filters
* Resident page with embeds, links, text formatting
* Event overview page w/ working links and filters
* Event page with embeds, links, text formatting
* Support overview page w/ working links and filters
* Homepage w/ carousel 

2nd Priority
* Side navigation
* Resident Resources section w/ login
* Search (needs design)
* Media pop-ups (needs design)

**Comment by coreytegeler** [comment]
@phillubliner what do you mean by "page editing abilities"

**Comment by phillubliner** [comment]
@coreytegeler Nm that, I see it's pulling text from other pages.

**Comment by phillubliner** [comment]
@coreytegeler Adding side navigation to 2nd priority
