### ISSUE TITLE
Gallery images: add new parsed dimension fields

### ISSUE THREAD

**Issue by phillubliner** [OtherMeans/iscp-wp-theme#91]
Override existing dimension fields if new fields are filled in.

____(height) x ______(width) x _______(depth) inches 
____(height) x ______(width) x _______(depth) cm

**Comment by phillubliner** [comment]
Cm should display as decimals rounded to nearest hundredth.

**Comment by phillubliner** [comment]
if a dimension field is left blank, remove the extra 'x' and the 0.

**Comment by coreytegeler** [comment]
i can only do that if the depth is missing, if there is no height it needs the 0 to prevent it from writing W x D or H x D

**Comment by phillubliner** [comment]
ok

**Comment by phillubliner** [comment]
:+1:
