### ISSUE TITLE
Setup WP Backup

### ISSUE THREAD

**Issue by coreytegeler** [OtherMeans/iscp-wp-theme#98]
[via Dropbox](https://wordpress.org/plugins/dropbox-backup/)?

**Comment by phillubliner** [comment]
How big is it?

**Comment by phillubliner** [comment]
Let's do this before the pre-2010 import.

**Comment by coreytegeler** [comment]
using [UpdraftPlus](https://wordpress.org/plugins/updraftplus/) to backup directly on the FTP

we can also set it up with dropbox, google drive, etc.
